# 项目相关配置
wshsoft:
  # 名称
  name: wshsoft
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件上传
  # 文件路径 示例（ Windows配置D:/tmp/uploadPath，Linux配置 /tmp/uploadPath）
  profile: D:/tmp/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 菜单导航显示风格（default为左侧导航菜单，topnav为顶部导航菜单）
  menuStyle: default

# 开发环境配置
# Server settings
server:
    # 服务器的HTTP端口，默认为80
    port: 80
    servlet:
      #应用的访问路径
      context-path: /
    # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
    max-http-header-size: 8192
    use-forward-headers: true
    compression:
        enabled: true
        min-response-size: 1024
        mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
    tomcat:
        remote-ip-header: X-Forwarded-for
        protocol-header: X-Forwarded-Proto
        port-header: X-Forwarded-Port
        # 存放Tomcat的日志目录
        basedir: /var/tomcat
        accesslog: 
          # 开启日志记录
          enabled: true
          # 访问日志存放目录
          directory: logs
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30    
# 日志配置
logging:
  level:
    com.wshsoft: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
    #打印sql语句和入参数据的配置
    #com.wshsoft.sys.mapper: debug
    
# 用户配置
user:
  password:
    # 密码错误次锁定
    maxRetryCount: 5
    #锁定时间默认30分钟
    maxLockTime: 30
# Spring配置
spring:       
  # 模板引擎
    thymeleaf:
        mode: HTML
        suffix: .html
        encoding: utf-8
        # 禁用缓存
        cache: false
        content-type: text/html
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    profiles: 
      include: druid,mybatisplus
      
    ##数据库创建#
    flyway:
      baseline-on-migrate: true
      locations: classpath:/db/sql #默认classpath:/db/migration
      check-location: true
      enabled: true
       
    # 文件上传
    servlet:
       multipart:
       # 单个文件大小
         max-file-size:  10MB
       # 设置总上传的文件大小
         max-request-size:  30MB
    # 服务模块
    devtools:
      restart:
        # 热部署开关
        enabled: true
    http:
        multipart:
            max-file-size: 2MB
            max-request-size: 10MB
        encoding:
            enabled: true
            charset: UTF-8
            force: true
    messages:
        encoding: UTF-8
        # 国际化资源文件路径
        basename: static/i18n/messages
    jmx:
        enabled: true
        default-domain: agentservice
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    # redis缓存服务配置
    session:
        store-type: redis
    # Redis数据库索引（默认为0）
    redis:
        database: 10
        # Redis服务器地址
        host: 115.236.19.6
        # Redis服务器连接端口
        port: 10009
        # Redis服务器连接密码（默认为空）
        password: aNOGMMK3zU2A
        # 连接池最大连接数（使用负值表示没有限制）
        pool:
            maxActive: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            maxWait: -1
            # 连接池中的最大空闲连接
            maxIdle: 8
            # 连接池中的最小空闲连接
            minIdle: 0
        # 连接超时时间（毫秒）
        timeout: 0
        # 默认的数据过期时间，主要用于shiro权限管理
        expire: 2592000
     
banner:
    charset: UTF-8
            
# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: char
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString(deskey.getEncoded()));
    cipherKey: 1QWLxg+NYmxraMoxAXu/Iw==
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
